apiVersion: v1
kind: Secret
metadata:
  name: jwt-app-secret # Deployment YAML에서 참조하는 Secret 이름
type: Opaque # 일반적인 Secret 타입
data:
  secretkey: eW91clZhbGlkQmFzZTY0RW5jb2RlZFNlY3JldEtleUdvZXNIZXJleW91clZhbGlkQmFzZTY0RW5jb2RlZFNlY3JldEtleUdvZXNIZXJleW91clZhbGlkQmFzZTY0RW5jb2RlZFNlY3JldEtleUdvZXNIZXJlPQ==
 # 'secretkey'는 Deployment YAML의 valueFrom.secretKeyRef.key 값과 일치해야 한다. # 원본 JWT 비밀키 문자열을 Base64로 인코딩한 결과여야 한다. 